### ISSUE TITLE
Transactions not Automatically Posting

### ISSUE THREAD

**Issue by Silvenga** [actualbudget/releases#111]
Given the scheduled transaction: 
![image](https://user-images.githubusercontent.com/2753330/143256301-41b5d681-9c0a-49dd-8f24-2db2f3d65f66.png)

Note that the "Automatically add transaction" button is checked and that the post date is the 22nd.

The transactions are not posting:

![image](https://user-images.githubusercontent.com/2753330/143256573-9461d2d4-1797-46e7-988c-4b7f0cac90e4.png)

**Comment by Silvenga** [comment]
This appears related to #93 as I see the same error when attempting to post some of my transactions.

**Comment by Kidglove57** [comment]
This one seems odd as only effects some users? All my transactions post perfectly and have done for some months.

**Comment by Silvenga** [comment]
@Kidglove57 bugs are more likely to not affect all users - survivorship bias may make it look otherwise.

**Comment by jlongster** [comment]
@Silvenga I _think_ this is fixed in 0.0.145. Please re-open this and let me know if it's not fixed!

**Comment by Silvenga** [comment]
Yep! Looks good now, thanks!
