### ISSUE TITLE
Rule with Amount as Criteria not Working

### ISSUE THREAD

**Issue by ssilence5** [actualbudget/releases#128]
I am having an issue with trying to setup a rule that is based on Amount (tried all three) and I cannot get it to work. I open the drop down and select any of the amounts and the drop down does not close. The next selection for comparison type doesn't update. It's almost like it is hanging or not sure how to handle an amount type. Anyone else seeing this?

https://actualbudget.slack.com/archives/CJ46FPL64/p1638277951215400

**Comment by smathson** [comment]
Looks like the same issue as #52 and should be resolved in the next release!

**Comment by ssilence5** [comment]
Looks to be the same problem. I will check it when the release comes out.
