### ISSUE TITLE
When creating a split transaction on android, you can save the transaction even if the remainder is nonzero

### ISSUE THREAD

**Issue by samschr** [actualbudget/releases#134]
How to reproduce: Create a transaction on mobile, add payee and total. Split to two different categories, and either leave both amounts at zero or set them to an amount that doesn't sum up to the correct total. Save the transaction.

What should happen: There should be a warning or something preventing saving a transaction without all the splits adding up to the transaction total. 

In the desktop app, this looks to be prevented entirely. The "Add Transaction" button is replaced by an "Add Split" button, and only turns back into "Add Transaction" once all the splits add up to the correct total.

**Comment by rich-howell** [comment]
Hey @samschr 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
