### ISSUE TITLE
Deleting a Category Requires "Reset budget cache"

### ISSUE THREAD

**Issue by Silvenga** [actualbudget/releases#140]
I attempt to delete a category with existing transactions (Wish Farm methodology). The delete executed correctly and the transactions were re-categorized, but the budget view was incorrect. I had to use the "Reset budget cache" button to correct the view. I was able to reproduce this twice.

Version: 0.0.144

**Comment by Silvenga** [comment]
Undoing the operation also requires a "Reset budget cache" before the budget is correct again.

**Comment by Silvenga** [comment]
Oh, this is odd. This only happens when deleting a category and moving the transactions to one of my more "complex" category. Moving to an empty category doesn't have problems.

**Comment by jlongster** [comment]
Known issue and I'm working on a fix! Thanks for reporting!

**Comment by jlongster** [comment]
Fixed in 0.0.145
