### ISSUE TITLE
"Invalid file type" error message when importing a .qif file

### ISSUE THREAD

**Issue by kuroikyu** [actualbudget/releases#16]
Hi,

I might be doing something wrong but I've tried importing a sample .qif file using [wikipedia's QIF page](https://en.wikipedia.org/wiki/Quicken_Interchange_Format) as source for the formatting and it doesn't work. I get a red toast that just says "Invalid file type".

Here's the contents of the .qif file I created:

```qif
!Type:Bank
D03/03/10
T-379.00
PCITY OF SPRINGFIELD
^
D03/04/10
T-20.28
PYOUR LOCAL SUPERMARKET
^
D03/03/10
T-421.35
PSPRINGFIELD WATER UTILITY
^
```

Not sure if related but I changed the date format setting to `DD/MM/YYYY` since I live in Europe but reverting to `MM/DD/YYYY` didn't fix the issue.

Let me know if there's anything I can do to help you debug this.

Thank you,
Kuroi

**Comment by jlongster** [comment]
Responded on twitter! https://twitter.com/jlongster/status/1090258262367264769

I'm not going to actively watch for issues here. There is a [Spectrum community](https://spectrum.chat/?t=670a990d-f333-47de-8c85-41a557e4c78a) that I'd prefer people to use (feel free to jump into the general thread)
