### ISSUE TITLE
Possible bug in label "Cleared total:"

### ISSUE THREAD

**Issue by alehel** [actualbudget/releases#167]
![image](https://user-images.githubusercontent.com/22277624/148072936-801febde-b0be-48fe-96d1-30943685e7ba.png)

I noticed that the sum next to the label "Cleared total" in the Accounts screen is the total for all my transactions. Both Cleared and not cleared. Isn't it the green number that is the cleared total?

**Comment by Deguello** [comment]
Green number is total balance of everything in the register. It is your cleared total plus your uncleared total. The math in that screenshot is right.

**Comment by alehel** [comment]
Ah. Now I finally understand. I was thinking about it completely wrong.
