### ISSUE TITLE
Feature: Add ability to see group names in the register

### ISSUE THREAD

**Issue by irandamay** [actualbudget/releases#169]
It would be nice to see what group something came from in the account registers in addition to the category, for categories with the same name, e.g. I have a category called "Food" under my "Flexible" monthly bills group (for people food) and "Pets" for the dogs, but in the registers I can't easily scan and see which "Food" something is applying to.  

I ended up duplicating the group name in the category name for things like that, but it doesn't look very nice in the actual budget list.

**Comment by Deguello** [comment]
Agreed. I have lists of names of people under Christmas and Reimbursements. I ended up changing Gas to Fuel for my car because I also have Gas under utilities.
