### ISSUE TITLE
editing a split in mobile

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/releases#170]
on Android, when I attempt to edit a category on a split transaction, it takes me to the category list, I select the new category, then it shows a sort of smaller input box "Edit Split Transaction" where I can select the new category, or change the amount, or add notes.  However, there's no "Done" or "complete" or "go back to New Transaction" button.  The only thing I can figure out to do is hit "back" (on the phone) and when I do that, it completely removes me from the transaction I was editing, and takes me back to the account register.

**Comment by rich-howell** [comment]
Hey @bpaulien 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
