### ISSUE TITLE
Null/blank payees showing up in the list

### ISSUE THREAD

**Issue by danrlavoie** [actualbudget/releases#189]
![blank](https://user-images.githubusercontent.com/3254579/152658827-0fa3d76f-7c37-41c3-a7a4-d5104a1e7a78.gif)

I'm not sure how this happened, but my list of payees has been polluted with these blank/empty options at the top of the list.

I can't see them in my list of Payees from the overall menu:
![image](https://user-images.githubusercontent.com/3254579/152658890-31a3eab0-8239-40e7-9955-1e7da42a2a6f.png)

Unless, maybe, they're related to these blank _Transfer:_ entries at the bottom?

![image](https://user-images.githubusercontent.com/3254579/152658898-f37738d2-ac32-44da-9822-57efafc3029e.png)

At any rate, I can't figure out how they get created or how to delete them, but I'd appreciate if they went away.

**Comment by jlongster** [comment]
Agreed -- sorry about this, I think there's another issue about this and I'll try to find it. There's a root issue that I'm still trying to figure out, but will get this fixed soon!
