### ISSUE TITLE
Allow rules to create split transactions

### ISSUE THREAD

**Issue by jlongster** [actualbudget/releases#195]
As the title said. One action in a rule should be to split transactions.

**Comment by bpaulien** [comment]
An extra feature tied to splits being created by rules:

Would it be possible to have it split based on a % of the amount?  For instance some people might want to take a certain % out to cover paying taxes, or maybe take out 10% for tithe, or something.  It would be awesome if splits could be automated by %!

**Comment by jlongster** [comment]
Cleaning up & triaging issue; this is something that's going to happen soon but doing the next release in the day or two and this won't be in it
