### ISSUE TITLE
Transactions remain selected after they get removed from current view

### ISSUE THREAD

**Issue by jlongster** [actualbudget/releases#199]
I don't think I see an existing issue for this but this is something that's going to be fixed in the next version. If you have a bunch of transactions selected, if you do something that removes them from the current view (like moving to a different account) they remain selected. Deleting correctly removes them from the selection.

**Comment by bpaulien** [comment]
I think this one might be affected by this fix too...  could probably be closed?
https://github.com/actualbudget/releases/issues/63#issue-1054362394

**Comment by jlongster** [comment]
@bpaulien thanks much for this comment. It made me realize that #63 wasn't fully fixed with the first implementation actually, but I've now improved it and tested it fully with upcoming transactions and it will be fixed!
