### ISSUE TITLE
Android App: New Transaction Date field uses a calendar instead of plain-text

### ISSUE THREAD

**Issue by amoscar** [actualbudget/releases#201]
This is definitely a quality of life improvement. When adding a new transaction using the Android app, the date field would be better suited getting input using some kind of calendar widget rather than a plain text field. At the very least it should always default to the current date - it only sometimes does this, I think if I leave the app open the date stays as the one from the last transaction I entered.

Using app version 0.0.144 on Android 11

**Comment by Deguello** [comment]
Also https://github.com/actualbudget/releases/issues/70

**Comment by rich-howell** [comment]
Hey @amoscar 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
