### ISSUE TITLE
Android App:  Calculate Tools Often Missing

### ISSUE THREAD

**Issue by rft183** [actualbudget/releases#206]
The toolbar that should appear just above the keyboard does not always show up.  It should show up every time the Amount field is selected.  Sometimes it does not appear when I attempt to make a new entry, but it almost never appears when I select a different field and then switch back to the Amount field.

![Actual_Android_Correct](https://user-images.githubusercontent.com/1713451/154146657-98f9f9bc-95ef-4e4b-9e7f-1348e4e961da.png)
![IMG_20220215_144251_0125](https://user-images.githubusercontent.com/1713451/154146730-8d489a4d-9514-43f4-b8c5-9cc920f8ad8c.JPG)

**Comment by rich-howell** [comment]
Hey @rft183 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
