### ISSUE TITLE
Option to disable syncing

### ISSUE THREAD

**Issue by Pikafu** [actualbudget/releases#207]
For users like myself who only glance at the budget every 2 weeks and only need it on one device, is it possible to implement a option to disable syncing? I have read the documentation and understand that end-to-end encryption is an option, but I would like to have only one copy of my data on one device, and understand the risks. 

If this is already an option, I'm sorry, I just did not see it in the docs or in the app.

**Comment by aleahalsad** [comment]
Hi @Pikafu! We currently don't have an option to disable syncing, but there potentially will be in the future. Thanks for posting!

**Comment by Pikafu** [comment]
@aleahalsad 

`We currently don't have an option to disable syncing, but there potentially will be in the future.`

If there will potentially be this option in the future, why not leave this issue open so it's not hidden to future collaborators who will potentially work on it?
