### ISSUE TITLE
Cannot Access Budget Settings if Title is Too Long

### ISSUE THREAD

**Issue by Pikafu** [actualbudget/releases#208]
This pertains to the Desktop app.

If the budget's name exceeds the width of the sidebar, the settings are inaccessible. The workaround is to rename the budget to a shorter name, access settings, then name the budget back.

You can see that a longer name pushes the settings to the right
![image](https://user-images.githubusercontent.com/1774908/154413653-487aec62-dfd0-401d-b03a-e660d8711783.png)

If the budget name exceeds the sidebar width, you can still click on the gear icon, but it doesn't do anything. 
![image](https://user-images.githubusercontent.com/1774908/154413518-2c345840-6057-4484-8c0d-53c1f21c0a6b.png)

**Comment by jlongster** [comment]
Thanks! Just fix this.
