### ISSUE TITLE
Category names after a certain length can't be seen in full without selecting to edit the category name.

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/releases#215]
Column width should expand dynamically if there is room on the web page to fit the longest category name.
And if no room, the full name should show on mouse over.

**Comment by bpaulien** [comment]
There is also some discussion about this (in the Discussions tab) here:
https://github.com/actualbudget/releases/discussions/30#discussion-3676464

**Comment by Teprifer** [comment]
Closing in deference to the existing thread linked above.
