### ISSUE TITLE
Allow a split to include a transfer

### ISSUE THREAD

**Issue by chriskrycho** [actualbudget/releases#218]
Came here to say this:

> Also allow a split to be a transfer.

_Originally posted by @MiriamNZ in https://github.com/actualbudget/actual/issues/310

This is basically the only part of the nYNAB import that doesn't work for me!

---

Motivation: it's not unusual for us to have a “payment” to the grocery store which is mostly an actual transaction but then to also get $20 or $100 or whatever in cash out. The transaction is a *single* transaction from the point of view of reconciliation (what shows up on the bank statement etc.) but the withdrawal part is just a transfer into the Cash account. (And yes, we have a Cash account and do envelope/zero-style budgeting with our cash as well as our other accounts!)

**Comment by Rick-Thomas** [comment]
I have the same situation and am delaying going live with Actual waiting for this to be included...   Still using YNAB4 and any import into Actual flags these transactions as "uncategorized transactions"...   Was hoping this would be included in the new release (146)...   Waiting for an update to the roadmap to see when this would be included so's to finally make the switch...  In the meantime, supporting Actual...
