### ISSUE TITLE
Account total is wrong

### ISSUE THREAD

**Issue by jheimbach** [actualbudget/releases#237]
I'm using the app on multiple devices, in the browser version the total in the top of the account overview page is wrong.

One of my accounts shows a different total than the running balance, the total in the sidebar. On mobile and desktop app it is correct.

How can i figure out which version i'm running, so i can add the infos to this ticket?

**Comment by Kidglove57** [comment]
I believe this is a known issue which will be resolved very shortly  - see my comment and this response on Slack. https://actualbudget.slack.com/archives/CATCX77FG/p1647272570755819

Hope that helps!

**Comment by jheimbach** [comment]
Thx, great to hear!
