### ISSUE TITLE
Show both Cleared Balance and Balance Including Uncleared transactions on the Accounts Screen

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/releases#241]
Scenario, I have some recurring transactions that occur on Wednesday evening, which means I can't confirm actual has the right account balance on Wednesdays without using a calculator to add back on the transactions that haven't occurred yet.

By showing the cleared balance I can compare what is in actual to what is shown by my bank.
By also showing the balance including the uncleared transactions I can see what my balance will be once the transactions go through.

**Comment by MikeBishop** [comment]
Can you clarify what you're looking for that's different from this?
![image](https://user-images.githubusercontent.com/4273797/159667574-c3c3667e-d0b6-4f4c-815f-2ad350f860fb.png)

**Comment by Kidglove57** [comment]
I was wondering the same! Although expanding the balance breakdown (as shown in your screenshot) is not always particularly obvious to newcomers.

**Comment by Teprifer** [comment]
> Can you clarify what you're looking for that's different from this? ![image](https://user-images.githubusercontent.com/4273797/159667574-c3c3667e-d0b6-4f4c-815f-2ad350f860fb.png)

Oooo yeah I think Kidglove57 is on the money here, the expando only shows on mouse over, so it's not easily discoverable.

I'll close this issue and open one for making it more discoverable.

**Comment by Kidglove57** [comment]
Yes agreed. I now leave it permanently open and it "sticks" open between app launches.
