### ISSUE TITLE
Account Total in sidebar is different from Top of the account detail

### ISSUE THREAD

**Issue by pmamberti** [actualbudget/releases#242]
The correct amount is the one shown in the sidebar, however in the main account page, I seem to be over a certain specific amount.

I suspect this may be a bug introduced with the split transactions fix, as the missing reconciled amount matches exactly the amount I have for some recurring split transactions.

I know this was correct before because I checked on an un synced iPhone and the total is correct there.

Let me know if I can provide further info!

**Comment by THeK3nger** [comment]
I can confirm. I have the same issue.

**Comment by Kidglove57** [comment]
Definitely sounds like the same issue - that the next release is primed to fix.it is very disconcerting though to see those nonsense figures!

**Comment by pmamberti** [comment]
Hey @Kidglove57 if you have a link to what's been worked on for the next release, that would be great to add here. 

I can only find the [release notes page](https://actualbudget.com/blog/?filter=release), but it does not have any info for  `0.0.148`. 🤔

**Comment by Kidglove57** [comment]
Good point. I was going by a numbers of threads on Slack and the developers Slack post yesterday which read as follows:

"All likely related to the bug I’ve fixed on the beta site (https://app-next.actualbudget.com/) will get a release out this week, sorry I haven’t yet — got sick last week"

**Comment by Deguello** [comment]
Same issue. Manually clearing then unclearing the split transaction gets rid of the mismatch.

**Comment by pmamberti** [comment]
Going to close, as I tested and this was fixed in the app-next preview by running the 'fix splits' option.
