### ISSUE TITLE
Phone app: cleared not working

### ISSUE THREAD

**Issue by MiriamNZ** [actualbudget/releases#247]
I open a transaction, i choose the 'cleared' button. 
It shows cleared. 
I save the transaction: it is not cleared. 

I open a transaction, i choose the 'cleared' button. 
It shows cleared. 
I click into notes to confirm the change. 
I save the transaction: it is not cleared.

Iphone. IOS 15.4.1

**Comment by Kidglove57** [comment]
I am on iPhone (OS 15) as you are and the cleared/uncleared is sticking for me as soon as I press save.

Strange the different experiences.

**Comment by Deguello** [comment]
Also works for me on 15.4.1. If it were me, I'd delete the app and reinstall.

**Comment by MiriamNZ** [comment]
Next day cleared was working properly again. 
Weird glitch.
