### ISSUE TITLE
App in browser needs updating, but how?

### ISSUE THREAD

**Issue by MiriamNZ** [actualbudget/releases#250]
Actual launches in the browser but cannot sync. Message is that changes on the server cannot be applied because it needs updating. 

I cant see how to update on the browser app. 
I tried refreshing the window. 
I tried quit the browser (Safari) and restart it.

**Comment by Kidglove57** [comment]
I am sorry this is happening to you! I have not used the web app for a long time so I just logged in on my Mac. I tried Safari and Chrome - both synced perfectly for me. 

I don't have any debugging suggestions but perhaps others have more experience?

Just a thought - have you tried signing out and then back in again?

**Comment by Deguello** [comment]
Maybe try the Reset Sync option in the Settings of the mobile app to try to get all devices working together.

**Comment by Kidglove57** [comment]
Thanks for explaining that this is Safari on iPad. I suggest the reset sync is started from a device where you know that the data is fully up to date. Good luck!

**Comment by rich-howell** [comment]
I suspect this has been fixed now. If the issue still persists, please open a fresh issue.
