### ISSUE TITLE
Disappearing Payees on Android

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/releases#47]
Can't confirm whether this also happens on iOS, but on my Android 11 device I see the following:

- Launch app
- Long-press Accounts to enter new transaction
- Type in the name of a new Payee
- Select "Create new Payee named..."

EXPECTED:  Payee name is in Payee box
ACTUAL:  Payee name is blank

- Select account for transaction
- Save transaction
- Navigate to account register

EXPECTED:  Transaction appears with Payee name
ACTUAL:  Transaction appears with _Empty_ as the Payee name

**Comment by brooksnt** [comment]
I also see this issue exactly as described by MikeBishop on my Android 11 device.

**Comment by bpaulien** [comment]
Awesome, glad I'm reading this...  I didn't even know that was a shortcut for creating a new transaction!  But to bring this back on topic...  Yes, I'm seeing the same thing.

**Comment by Kidglove57** [comment]
The difference for me (on iOS) is that the payee does not appear as “empty” once posted - only before posting. In other words the “invisible” payee that I select in the transaction entry dialogue appears correctly in the account register.

**Comment by tjfinlinson** [comment]
I used to have this issue, and for me it was like how @Kidglove57  described it. I'm on Android 12. Today when testing the scenario, it kept the payee name in the field. Just reporting this behavior Incase it can help narrow something down.

I did a long press on the accounts button, did a search for a payee, and also did the same steps directly on the account page. Both gave me the expected result of displaying the payee.

**Comment by MikeBishop** [comment]
> The difference for me (on iOS) is that the payee does not appear as “empty” once posted - only before posting. In other words the “invisible” payee that I select in the transaction entry dialogue appears correctly in the account register.

Sometimes that's the case for me, so I enter the transaction anyway and hope.  I haven't found a pattern to that, yet.

I have, however, noticed that if I type the Payee again **and create a second Payee of that name** (which I shouldn't be able to do, I'd think), then both Payees work just fine.  That maybe smells like an off-by-one error somewhere?

**Comment by rich-howell** [comment]
Hey @MikeBishop 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
