### ISSUE TITLE
Usability:  Long-pressing Accounts on mobile is completely undiscoverable

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/releases#49]
There exists an option in the app to enter a transaction without navigating to a particular account simply by long-pressing the Accounts icon.  However, there is no UI clue that this is even a possibility -- and yet, this is arguably the most important workflow in the mobile app.  Consider giving "Add Transaction" its own icon or otherwise having a front-and-center way of getting to that screen.

Without it, I suspect you'll get a lot of requests (or silent wishes) for functionality you already have.

**Comment by bzupnick** [comment]
+1

I was one of the silent wishers

**Comment by makenova** [comment]
neat. I've been using the mobile app for months and always just used the "+" in the top right corner.
@MikeBishop How did you find that?

**Comment by MikeBishop** [comment]
Asked for the feature and was told it already existed.

**Comment by rich-howell** [comment]
Hey @MikeBishop 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
