### ISSUE TITLE
Edit Categories on Mobile can't edit Income categories

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/releases#55]
When moving into the Edit Categories view on Android, the Income categories appear to remain as they normally are, not modifiable. Is this Desktop-only functionality?

**Comment by rich-howell** [comment]
Hey @MikeBishop 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
