### ISSUE TITLE
Mobile (seen on iOS) transaction entry should use a datepicker widget.

### ISSUE THREAD

**Issue by Deguello** [actualbudget/releases#70]
Free text entry is more error-prone and almost always takes longer.

**Comment by btrautmann** [comment]
+1000, this is the biggest drawback to the current transaction entry process!

**Comment by ColGra** [comment]
+1

**Comment by rich-howell** [comment]
Hey @Deguello 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich
