### ISSUE TITLE
Can't post upcoming Schedule transactions

### ISSUE THREAD

**Issue by Deguello** [actualbudget/releases#93]
When I try to post, I get what appears to be the standard error handler message: Something internally went wrong. You may want to restart the app if anything looks wrong. We have been notified of the issue and will try to fix it soon

Multiple transactions. Multiple accounts. Multiple restarts. Nothing is working.

**Comment by Deguello** [comment]
For the record:

Actual
Version 0.0.144
All up to date!

**Comment by ColGra** [comment]
Just posted an "upcoming" scheduled transaction on the desktop app and it worked as expected. Same version as you and on Mac. Did same on the web app and no issues.

**Comment by Deguello** [comment]
I'm glad it works for you, but that doesn't change the error.

<img width="601" alt="Screen Shot 2021-11-19 at 9 35 02 AM" src="https://user-images.githubusercontent.com/16468471/142649185-787a2114-0db8-4609-a020-995976eeb789.png">

**Comment by MiriamNZ** [comment]
Have you tried resetting the cache?

**Comment by Deguello** [comment]
How do I reset the cache on the desktop client?

**Comment by Deguello** [comment]
I don't if it would make any difference, but both of the transactions that are failing are using the BETWEEN option for the amount.

**Comment by ColGra** [comment]
No, @Deguello, but it does prove it is not a universal fault, which is important. That said, I note you have brought another piece of info to the table. What is the BETWEEN option - ah, found it. I have never found a need for that for that.

**Comment by Deguello** [comment]
Changing the amount to EXACTLY or APPROXIMATELY allows the transaction to be posted. Seems to be a flaw with BETWEEN.

**Comment by samschr** [comment]
Might be related, but I get the same error when trying to post a "missed" transaction a day after it was scheduled.

**Comment by Silvenga** [comment]
@samschr was the transaction never auto-posted (and it should have been)? Similar to https://github.com/actualbudget/releases/issues/111?

**Comment by samschr** [comment]
I don't do any bank sync or transaction file import, I manually add every transaction as I make them (usually in the mobile app), and then double check (reconcile in YNAB) any recurring / automatic transactions about once a week. So yes, on my bank's side, the transaction did in fact post, but actualbudget still says it's missed.

**Comment by Silvenga** [comment]
And you have the auto-post checkbox enabled in Actual @samschr?
